In [1]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [2]:
df = sns.load_dataset('iris')
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
x= df.drop("species" , axis =1)
y= df['species']

In [5]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [6]:
#whenever you are doing ensemble model you have to do train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y_encoded,test_size=0.20 , random_state=42,stratify=y_encoded)

In [7]:
#now use base learnes :- 
base_learners = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svc' , SVC(probability=True , kernel='rbf' , random_state=42)), 
    ('lr' , LogisticRegression(max_iter=1000))
]

In [8]:
meta_learner = LogisticRegression(max_iter=1000)

In [9]:
stacking_clf = StackingClassifier(
    estimators=base_learners , 
    final_estimator=meta_learner, 
    cv=5
)

In [10]:
stacking_clf.fit(x_train,y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [11]:
accuracy = accuracy_score(y_test , y_pred=stacking_clf.predict(x_test))

In [12]:
accuracy

0.9666666666666667

**Using RAndom forest**

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
rf_model = RandomForestClassifier(
    n_estimators=100,  #Number o trees
    max_depth=None ,    #let tree grow fully
    random_state=42
)

In [15]:
rf_model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [16]:
y_pred_rf = rf_model.predict(x_test)

In [17]:
accuracy = accuracy_score(y_test , y_pred_rf)

In [18]:
accuracy

0.9

**LET USE BOOSTING TYPES**

In [19]:
from sklearn.ensemble import AdaBoostClassifier ,GradientBoostingClassifier

In [20]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\shiva\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\shiva\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\users\shiva\anaconda3\lib\site-packages (from xgboost) (1.15.3)

In [21]:
import xgboost as xgb

In [22]:
ada_model = AdaBoostClassifier(n_estimators=100 , random_state=42)

In [28]:
ada_model.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [29]:
y_pred_ada = ada_model.predict(x_test)

In [30]:
accuracy_ada = accuracy_score(y_test , y_pred_ada)

In [31]:
accuracy_ada

0.9333333333333333

In [32]:
#now use GradientBoostingClassifier
gradient_booster_model = GradientBoostingClassifier(n_estimators=100 , learning_rate=0.1 , random_state=42)

In [33]:
gradient_booster_model.fit(x_train,y_train)

GradientBoostingClassifier(random_state=42)

In [34]:
y_pred_gra_booster = gradient_booster_model.predict(x_test)

In [36]:
accuracy_gra_booster = accuracy_score(y_test , y_pred_gra_booster) 
accuracy_gra_booster

0.9666666666666667

In [38]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

In [42]:
import warnings
warnings.filterwarnings("ignore")


xgb_model.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [43]:
y_pred_xgb = xgb_model.predict(x_test)

In [44]:
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
accuracy_xgb

0.9333333333333333