In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [4]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [6]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x = df.drop('species' , axis =1)
y= df['species']

In [10]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
model_knn  = KNeighborsClassifier(n_neighbors = 5)

In [13]:
model_knn.fit(x_train , y_train)

KNeighborsClassifier()

In [14]:
model_knn.score(x_test , y_test)

0.98

In [15]:
#now let me change my n_neighbors from 5 to 9 
model_knn  = KNeighborsClassifier(n_neighbors = 9) 
model_knn.fit(x_train , y_train) 
model_knn.score(x_test , y_test)

0.98

In [16]:
#now let me change my n_neighbors from 5 to 13
model_knn  = KNeighborsClassifier(n_neighbors = 13) 
model_knn.fit(x_train , y_train) 
model_knn.score(x_test , y_test)

1.0

In [17]:
from sklearn.svm import SVC

In [18]:
model_svm = SVC(gamma='auto' , C=30 , kernel='rbf')  #c can be say as punishment 
model_svm.fit(x_train , y_train) 
model_svm.score(x_test , y_test)

0.98

In [19]:
# let use a linear kernel 
model_svm = SVC(gamma='auto' , C=30 , kernel='linear')  #c can be say as punishment 
model_svm.fit(x_train , y_train) 
model_svm.score(x_test , y_test)

0.98

In [20]:
# let use C=10 
model_svm = SVC(gamma='auto' , C=10 , kernel='linear')  #c can be say as punishment 
model_svm.fit(x_train , y_train) 
model_svm.score(x_test , y_test)

1.0

In [21]:
#Now lets use the Grid Search CV

In [22]:
from sklearn.model_selection import GridSearchCV

In [23]:
#after importing lets use hyper parameter tuning and creat grids 
#So to perform GridsearchCV we need to select model let us select model_svm 
classifire = GridSearchCV((model_svm),{
    "C" :[1,10,20,30] , 
    "kernel" :['rbf' , 'linear'] , 
}, cv=5,return_train_score = False)

In [24]:
classifire.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [25]:
classifire.cv_results_

{'mean_fit_time': array([0.00456972, 0.00411391, 0.00428596, 0.00419612, 0.00384145,
        0.00442119, 0.00426931, 0.00474195]),
 'std_fit_time': array([0.00060339, 0.00036628, 0.00043221, 0.0003425 , 0.00015025,
        0.00073608, 0.00051162, 0.00125006]),
 'mean_score_time': array([0.00332832, 0.00303431, 0.00341306, 0.00334864, 0.00308208,
        0.00347509, 0.00330801, 0.00346646]),
 'std_score_time': array([0.00050996, 0.00029714, 0.00060752, 0.00058268, 0.00014473,
        0.00047795, 0.00038559, 0.00077099]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [26]:
results = pd.DataFrame(classifire.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004570,0.000603,0.003328,0.000510,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004114,0.000366,0.003034,0.000297,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004286,0.000432,0.003413,0.000608,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.004196,0.000342,0.003349,0.000583,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.003841,0.000150,0.003082,0.000145,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.004421,0.000736,0.003475,0.000478,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.004269,0.000512,0.003308,0.000386,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.004742,0.001250,0.003466,0.000771,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [27]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [28]:
#lets do same thing for KNN
classifire_knn = GridSearchCV(
    model_knn,
    {
        "n_neighbors": [3, 5, 7, 9, 11],
        "weights": ["uniform", "distance"],
        "metric": ["euclidean", "manhattan", "minkowski"]
    },
    cv=5,
    return_train_score=False
)

In [29]:
classifire_knn.fit(x,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']})

In [30]:
results_knn = pd.DataFrame(classifire_knn.cv_results_)
results_knn

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004272,0.000919,0.007089,0.001020,euclidean,3,uniform,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,17
1,0.003799,0.000196,0.004058,0.000253,euclidean,3,distance,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,17
2,0.003913,0.000448,0.007892,0.001380,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,10
3,0.003565,0.000264,0.004425,0.000931,euclidean,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,17
4,0.004002,0.000663,0.007938,0.001003,euclidean,7,uniform,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,3
5,0.004308,0.001014,0.004651,0.000751,euclidean,7,distance,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,3
6,0.003424,0.000079,0.007423,0.000913,euclidean,9,uniform,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,10
7,0.003581,0.000437,0.003913,0.000239,euclidean,9,distance,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,10
8,0.003731,0.000241,0.008150,0.000923,euclidean,11,uniform,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,3
9,0.003739,0.000356,0.004597,0.001301,euclidean,11,distance,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
10,0.004195,0.001217,0.006977,0.000482,manhattan,3,uniform,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,29
11,0.003683,0.000209,0.004062,0.000630,manhattan,3,distance,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,29
12,0.003783,0.001028,0.006557,0.000398,manhattan,5,uniform,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,25
13,0.004595,0.001064,0.003928,0.000445,manhattan,5,distance,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,25
14,0.004191,0.000434,0.007016,0.000513,manhattan,7,uniform,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,10
15,0.003719,0.000183,0.004930,0.000988,manhattan,7,distance,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,25
16,0.003426,0.000173,0.006938,0.000296,manhattan,9,uniform,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.933333,0.933333,1.0,0.966667,0.029814,17
17,0.003443,0.000317,0.005458,0.002037,manhattan,9,distance,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,25
18,0.003976,0.000624,0.007031,0.000497,manhattan,11,uniform,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,3
19,0.004232,0.000915,0.004923,0.000752,manhattan,11,distance,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,17
20,0.003373,0.000307,0.007208,0.000945,minkowski,3,uniform,"{'metric': 'minkowski', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,17
21,0.003830,0.000634,0.003882,0.000192,minkowski,3,distance,"{'metric': 'minkowski', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,17
22,0.003595,0.000131,0.007406,0.001262,minkowski,5,uniform,"{'metric': 'minkowski', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,10
23,0.003796,0.000380,0.003927,0.000350,minkowski,5,distance,"{'metric': 'minkowski', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,17
24,0.003567,0.000233,0.007205,0.000935,minkowski,7,uniform,"{'metric': 'minkowski', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,3
25,0.003529,0.000285,0.003927,0.000233,minkowski,7,distance,"{'metric': 'minkowski', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,3
26,0.003589,0.000237,0.007590,0.001363,minkowski,9,uniform,"{'metric': 'minkowski', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,10
27,0.003712,0.000211,0.004405,0.000652,minkowski,9,distance,"{'metric': 'minkowski', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,10
28,0.003527,0.000306,0.007331,0.000730,minkowski,11,uniform,"{'metric': 'minkowski', 'n_neighbors': 11, 'we...",0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,3
29,0.003533,0.000254,0.003972,0.000265,minkowski,11,distance,"{'metric': 'minkowski', 'n_neighbors': 11, 'we...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1

In [31]:
results_knn[['param_n_neighbors', 'param_weights', 'param_metric', 'mean_test_score']]

    param_n_neighbors param_weights param_metric  mean_test_score
0                   3       uniform    euclidean         0.966667
1                   3      distance    euclidean         0.966667
2                   5       uniform    euclidean         0.973333
3                   5      distance    euclidean         0.966667
4                   7       uniform    euclidean         0.980000
5                   7      distance    euclidean         0.980000
6                   9       uniform    euclidean         0.973333
7                   9      distance    euclidean         0.973333
8                  11       uniform    euclidean         0.980000
9                  11      distance    euclidean         0.986667
10                  3       uniform    manhattan         0.960000
11                  3      distance    manhattan         0.960000
12                  5       uniform    manhattan         0.960000
13                  5      distance    manhattan         0.960000
14                  7       uniform    manhattan         0.973333
15                  7      distance    manhattan         0.960000
16                  9       uniform    manhattan         0.966667
17                  9      distance    manhattan         0.960000
18                 11       uniform    manhattan         0.980000
19                 11      distance    manhattan         0.966667
20                  3       uniform    minkowski         0.966667
21                  3      distance    minkowski         0.966667
22                  5       uniform    minkowski         0.973333
23                  5      distance    minkowski         0.966667
24                  7       uniform    minkowski         0.980000
25                  7      distance    minkowski         0.980000
26                  9       uniform    minkowski         0.973333
27                  9      distance    minkowski         0.973333
28                 11       uniform    minkowski         0.980000
29                 11      distance    minkowski         0.986667

**USE RANDOM SEARCH CV**

In [32]:
from sklearn.model_selection import RandomizedSearchCV

In [33]:
classifire_rdcv = RandomizedSearchCV((model_svm),{
    "C" :[1,10,20,30] , 
    "kernel" :['rbf' , 'linear'] , 
}, n_iter = 4 , cv=5,return_train_score = False)

In [34]:
classifire_rdcv.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
                   n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [35]:
results_rdcv = pd.DataFrame(classifire_rdcv.cv_results_)
results_rdcv

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005015,0.001489,0.003153,0.000264,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4
1,0.004403,0.000451,0.003821,0.000339,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004578,0.000511,0.003171,0.000277,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,3
3,0.004558,0.000888,0.004030,0.000402,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [36]:
results_rdcv[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       30       linear         0.960000
1        1          rbf         0.980000
2       20       linear         0.966667
3       10          rbf         0.980000